# https://static-web-server.net/configuration/config-file/

[general]
host = "::"
port = 3004
root = "./assets"

log-level = "info"

page404 = ".404.html"  # site/.404.html
page50x = ".50x.html"  # site/.50x.html

compression-static = true


[advanced]

[[advanced.headers]]
source = "**/*.{html,js,css,png,ico,json,xml}"
headers = {Cache-Control = "no-cache, no-store, must-revalidate", Pragma = "no-cache", Expires = "0"}
